### PR TITLE
Fix bad indent

### PR DESCRIPTION
**Pull request by NickBorgers**
Looks like this repo could use some linters as Actions and/or githooks.

I'm looking at possibly pushing for adoption of this spec so willing to do some work. Has linting on the Action pipeline already been implemented? Any specific approach that seems like it would be preferred/better?

### CODE REVIEW

**Comment by eitsupi** [comment]
The previous repository, https://github.com/microsoft/vscode-dev-containers, used editorconfig, but it does not appear to be in this repository.
It is possible that some decision has been made.

**Comment by NickBorgers** [comment]
> The previous repository, https://github.com/microsoft/vscode-dev-containers, used editorconfig, but it does not appear to be in this repository. It is possible that some decision has been made.

Looking at the announcement in that README also reveals to me that Devcontainer being an open spec is new. I was wondering how I missed that before...

**Comment by samruddhikhandale** [comment]
> The previous repository, https://github.com/microsoft/vscode-dev-containers, used editorconfig, but it does not appear to be in this repository. It is possible that some decision has been made.

Thanks! Looks like it was missed while migrating images to this repository. I'll open up a PR 👍

**Review by samruddhikhandale — APPROVED** [review]
Thanks!

**Pull request merged**
