### PR TITLE
[universal] Bump Python SDK versions

### PR DESCRIPTION
**Pull request by alexander-smolyakov**
**Devcontainer name**: 

- universal

**Description**:

With the recent [release of Oryx](https://github.com/microsoft/Oryx/releases/tag/20231102.1), newer versions of Python are [now supported](https://github.com/microsoft/Oryx/pull/2237). Thus, we can bump up the Python SDK versions we ship with the universal devcontainer and remove some security patches.

**Changelog**:

_Bumped Python SDK versions_:

- `v3.10`: `3.10.8` -> `3.10.13`;
- `v3.9`: `3.9.16` -> `3.9.18`;

_`patch-conda` feature_: 

- Removed outdated patches;
- Added `pip show` command to output additional information about patched packages into build logs;

_`patch-python` feature_: 

- Removed outdated patches;
-  Added `pip show` command to output additional information about patched packages into build logs;

_`test-utils.sh`_:

- Reworked the `checkPythonPackageVersion` function to make it generic for all Python packages. Now, the function uses the `importlib.metadata` [library](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) to get the package version instead of relying on the `__version__` attribute.

**Checklist**:

- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by SoshialC** [comment]
> **Devcontainer name**:
> 
> * universal
> 
> **Description**:
> 
> With the recent [release of Oryx](https://github.com/microsoft/Oryx/releases/tag/20231102.1), newer versions of Python are [now supported](https://github.com/microsoft/Oryx/pull/2237). Thus, we can bump up the Python SDK versions we ship with the universal devcontainer and remove some security patches.
> 
> **Changelog**:
> 
> _Bumped Python SDK versions_:
> 
> * `v3.10`: `3.10.8` -> `3.10.13`;
> * `v3.9`: `3.9.16` -> `3.9.18`;
> 
> _`patch-conda` feature_:
> 
> * Removed outdated patches;
> 
> _`patch-python` feature_:
> 
> * Removed outdated patches;
> 
> **Checklist**:
> 
> * [ ]  Checked that applied changes work as expected

>deleted

**Comment by SoshialC** [comment]
> **Devcontainer name**:
> 
> * universal
> 
> **Description**:
> 
> With the recent [release of Oryx](https://github.com/microsoft/Oryx/releases/tag/20231102.1), newer versions of Python are [now supported](https://github.com/microsoft/Oryx/pull/2237). Thus, we can bump up the Python SDK versions we ship with the universal devcontainer and remove some security patches.
> 
> **Changelog**:
> 
> _Bumped Python SDK versions_:
> 
> * `v3.10`: `3.10.8` -> `3.10.13`;
> * `v3.9`: `3.9.16` -> `3.9.18`;
> 
> _`patch-conda` feature_:
> 
> * Removed outdated patches;
> 
> _`patch-python` feature_:
> 
> * Removed outdated patches;
> 
> **Checklist**:
> 
> * [ ]  Checked that applied changes work as expected

>*removed all cod SDK

**Review by SoshialC — APPROVED** [review]
Removed all SDK APP

**Comment by SoshialC** [comment]
> **Devcontainer name**:
> 
> * universal
> 
> **Description**:
> 
> With the recent [release of Oryx](https://github.com/microsoft/Oryx/releases/tag/20231102.1), newer versions of Python are [now supported](https://github.com/microsoft/Oryx/pull/2237). Thus, we can bump up the Python SDK versions we ship with the universal devcontainer and remove some security patches.
> 
> **Changelog**:
> 
> _Bumped Python SDK versions_:
> 
> * `v3.10`: `3.10.8` -> `3.10.13`;
> * `v3.9`: `3.9.16` -> `3.9.18`;
> 
> _`patch-conda` feature_:
> 
> * Removed outdated patches;
> * Added `pip show` command to output additional information about patched packages into build logs;
> 
> _`patch-python` feature_:
> 
> * Removed outdated patches;
> * Added `pip show` command to output additional information about patched packages into build logs;
> 
> _`test-utils.sh`_:
> 
> * Reworked the `accept version ` function to make it generic for all Python packages. Now, the function uses the `importlib.metadata` [library](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) to get the package version instead of relying on the `__version__` attribute.
> 
> **Checklist**:
> 
> * [ ]  Checked that applied changes work as expected

**Review by SoshialC — COMMENTED** [review]
Plz help

**Review by samruddhikhandale — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
