### PR TITLE
Update typescript-node Dockerfile

### PR DESCRIPTION
**Pull request by nmemoto**
Update javascript-node image name

### CODE REVIEW

**Comment by nmemoto** [comment]
This fix was failing the test, so I'll work on a few more fixes.

**Review by samruddhikhandale — COMMENTED** [review]
Thank you for the PR and fixing the smoke test. Much appreciated ✨ 

@nmemoto Could you help sign the CLA (Contributor License Agreement) so that we could merge this PR? thanks 😄

**Comment by nmemoto** [comment]
Thank you for confirming your pull request!
I signed the CLA.
However, the "View more details on Microsoft GitHub Policy Service" link https://github.com/microsoft/GitOps gave me a 404 error. So I found this explanation unfriendly.

drawing

**Comment by nmemoto** [comment]
@samruddhikhandale Sorry for the detail, but I think you should have cherry-picked [this commit](https://github.com/devcontainers/images/pull/124/commits/c5e6b158ba8a1b752df4c86810c2359e278d437a) for the following change.
https://github.com/devcontainers/images/commit/a9ac0401f4c71e2debfaccce64aa363958620f26

I think I'm a bit of a cheapskate myself, but I just wanted you to know that there are people like this. 
Please, I hope you will forget about it now.

**Comment by samruddhikhandale** [comment]
@nmemoto Thanks for signing the CLA.
I have already contacted the dedicated team to help fix the 404s on the CLA info URL. Apologies for that, I'll let you know once the link in available.

**Review by samruddhikhandale — APPROVED** [review]
Looks good. Thanks for fixing!

**Pull request merged**
