### PR TITLE
[Anaconda] Address GHSA-q3qx-c6g2-7pw2 vulnerability

### PR DESCRIPTION
**Pull request by gauravsaini04**
**Dev container name**:
 
 * anaconda

 **Description**:
 
 This PR patches the following vulnerability:
 
 * [GHSA-q3qx-c6g2-7pw2](https://github.com/advisories/GHSA-q3qx-c6g2-7pw2) - related to the `aiohttp` package;
 
 This vulnerability comes from the continuumio/anaconda3 image used upstream for the anaconda devcontainer.
 
 _Changelog_:
 
 * Updated Dockerfile:
   
   * Locked version for patched Python package; 
     * `aiohttp` - _minimum package version set to `3.9.0`_;

 * Updated tests to verify aiohttp minimum version (Minimum package version set to 3.9.0 which fixes [GHSA-q3qx-c6g2-7pw2](https://github.com/advisories/GHSA-q3qx-c6g2-7pw2));
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

### CODE REVIEW

**Review by eljog — APPROVED** [review]

**Review by eljog — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

**Review by alexander-smolyakov — APPROVED** [review]

**Comment by gauravsaini04** [comment]
Merge conflicts have been resolved

**Review by eljog — APPROVED** [review]

**Review by eljog — CHANGES_REQUESTED** [review]
Resolve new merge conflicts

**Review by eljog — APPROVED** [review]
⚡

**Pull request merged**
